export const sideBarLink = [
  {
    id: 1,
    title: "Dashboard",
    srcLink: "",
    svg: "/images/sidebar/Dashboard.png",
    subMenu: [],
  },
  {
    id: 2,
    title: "Wallets",
    srcLink: "",
    svg: "/images/sidebar/Wallets.png",
    subMenu: [],
  },
  {
    id: 3,
    title: "Gas Station",
    srcLink: "",
    svg: "/images/sidebar/Gas Station.png",
    subMenu: [],
  },
  {
    id: 4,
    title: "Referrals",
    srcLink: "",
    svg: "/images/sidebar/Referrals.png",
    subMenu: [],
  },
  {
    id: 5,
    title: "Invoices",
    srcLink: "",
    svg: "/images/sidebar/Invoices.png",
    subMenu: [
      {
        id: 1,
        title: "Withdraw",
        srcLink: "",
      },
      {
        id: 2,
        title: "Deposit",
        srcLink: "",
      },
    ],
  },
  {
    id: 6,
    title: "Transactions",
    srcLink: "",
    svg: "/images/sidebar/Transactions.png",
    subMenu: [],
  },
  {
    id: 7,
    title: "Swap",
    srcLink: "",
    svg: "/images/sidebar/Swap.png",
    subMenu: [],
  },
  {
    id: 8,
    title: "Security",
    srcLink: "",
    svg: "/images/sidebar/Security.png",
    subMenu: [],
  },
  {
    id: 9,
    title: "Support",
    srcLink: "",
    svg: "/images/sidebar/Support.png",
    subMenu: [],
  },
  {
    id: 10,
    title: "Webhook",
    srcLink: "",
    svg: "/images/sidebar/Webhook.png",
    subMenu: [],
  },
  {
    id: 11,
    title: "Logs",
    srcLink: "",
    svg: "/images/sidebar/Logs.png",
    subMenu: [],
  },
  {
    id: 12,
    title: "IPNs",
    srcLink: "",
    svg: "/images/sidebar/IPNs.png",
    subMenu: [],
  },
];
