export const sort = [
  {
    id: 1,
    name: "Invoice ID",
    svg: "/images/AdvancedFilters/filter.png",
    subSort: [],
  },
  {
    id: 2,
    name: "Store",
    svg: "/images/AdvancedFilters/filter.png",
    subSort: [],
  },
  {
    id: 3,
    name: "Wallet",
    svg: "/images/AdvancedFilters/filter.png",
    subSort: [],
  },
  {
    id: 4,
    name: "Crypto amount",
    svg: "/images/AdvancedFilters/filter.png",
    subSort: [],
  },
  {
    id: 5,
    name: "Token & network",
    svg: "/images/AdvancedFilters/filter.png",
    subSort: [],
  },
  // {
  //   id: 4,
  //   name: "Value",
  //   svg: "/images/AdvancedFilters/filter.png",
  //   subSort: [
  //     "Equals to",
  //     "Not equals to",
  //     "Be equal to or greater than",
  //     "Greater than",
  //     "Be equal to or less than",
  //     "Less than",
  //     "Is null",
  //     "Is not null",
  //   ],
  // },
  {
    id: 6,
    name: "Date",
    svg: "/images/AdvancedFilters/filter.png",
    subSort: [],
  },
  {
    id: 7,
    name: "Status",
    svg: "/images/AdvancedFilters/filter.png",
    subSort: [],
  },
  {
    id: 8,
    name: "More",
    svg: "/images/AdvancedFilters/filter.png",
    subSort: [],
  },
];
