import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/layout/sideBar";
import MenuMobile from "@/components/layout/menuMobile";
import Header from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full relative flex bg-dark-800 h-screen ">
          <SideBar />
          <MenuMobile />

          <div className="w-full ">
            <Header />
            <div className=" px-3 sm:px-5 xl:px-10 py-[22px] mb-5 lg:mb-0">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
